<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>sporthub.api.host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\1.sporthub.repository\1.sporthub.repository.csproj" />
    <ProjectReference Include="..\2.sporthub.domain\2.sporthub.domain.csproj" />
    <ProjectReference Include="..\3.sporthub.app\3.sporthub.app.csproj" />
    <ProjectReference Include="..\4.sporthub.app.contracts\4.sporthub.app.contracts.csproj" />
    <ProjectReference Include="..\5.sporthub.api\5.sporthub.api.csproj" />
    <ProjectReference Include="..\..\shared_kernel_lib\src\Shared.Auth\Shared.Auth.csproj" />
  </ItemGroup>
</Project>
