<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>demo_project.domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="demo_project\**" />
    <EmbeddedResource Remove="demo_project\**" />
    <None Remove="demo_project\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include=".common\BaseModel.cs" />
    <Compile Include=".common\BaseParamsProcedure.cs" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="mini_cdp\internal\" />
  </ItemGroup>

</Project>
