<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>demo_project.api</RootNamespace>
	  <AssemblyName>demo_project.api</AssemblyName>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <!--<Nullable>enable</Nullable>-->
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DnsClient" Version="1.8.0" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.1.1" />
		<PackageReference Include="Grpc.AspNetCore.HealthChecks" Version="2.70.0" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.21" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.12.0-beta.1" />
		<PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.2.2" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\4.demo_project.app.contracts\4.demo_project.app.contracts.csproj" />
	  <ProjectReference Include="..\azicloud.api\azicloud.api.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="consume\" />
	  <Folder Include="demo_project\partner_auth\SSO\" />
	  <Folder Include="webhook\" />
	</ItemGroup>

</Project>
