<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>sporthub.repository</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\0.sporthub.shared\0.sporthub.shared.csproj" />
    <ProjectReference Include="..\2.sporthub.domain\2.sporthub.domain.csproj" />
  </ItemGroup>
</Project>