<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>sporthub.app.contracts</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\0.sporthub.shared\0.sporthub.shared.csproj" />
    <ProjectReference Include="..\..\shared_kernel_lib\src\Shared.Common\Shared.Common.csproj" />
  </ItemGroup>
</Project>