<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>demo_project.repository</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\0.demo_project.shared\0.demo_project.shared.csproj" />
    <ProjectReference Include="..\2.demo_project.domain\2.demo_project.domain.csproj" />
  </ItemGroup>

</Project>
