<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>demo_project.app</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include=".common\BaseAppService.cs" />
    <Compile Include=".common\BaseMapperProfile.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
	  <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.72.0.3966" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\0.demo_project.shared\0.demo_project.shared.csproj" />
    <ProjectReference Include="..\2.demo_project.domain\2.demo_project.domain.csproj" />
    <ProjectReference Include="..\4.demo_project.app.contracts\4.demo_project.app.contracts.csproj" />
    <ProjectReference Include="..\azicloud.app.contracts\azicloud.app.contracts.csproj" />
  </ItemGroup>

</Project>
