// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sporthub.repository;

#nullable disable

namespace sporthub.repository.context.migrations
{
    [DbContext(typeof(SportHubDbContext))]
    [Migration("20260817101811_InitialCreate_4")]
    partial class InitialCreate_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sporthub.domain.Address", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("addressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address_line");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_default")
                        .HasColumnType("bit");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("receiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("receiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("receiver_phone");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("user_id", "is_default");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Brand", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("logo_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Cart", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("user_id", "status");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.CartItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("cart_id")
                        .HasColumnType("bigint");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("product_variant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("unit_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("product_variant_id");

                    b.HasIndex("cart_id", "product_variant_id")
                        .IsUnique();

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("display_order")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("parent_id")
                        .HasColumnType("bigint");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("parent_id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.InventoryItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("product_variant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity_on_hand")
                        .HasColumnType("int");

                    b.Property<int>("reorder_level")
                        .HasColumnType("int");

                    b.Property<int>("reserved_quantity")
                        .HasColumnType("int");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("product_variant_id")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.InventoryTransaction", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<long?>("created_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("inventory_item_id")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<long?>("reference_id")
                        .HasColumnType("bigint");

                    b.Property<string>("reference_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("created_by_user_id");

                    b.HasIndex("inventory_item_id", "created_date");

                    b.HasIndex("reference_type", "reference_id");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Order", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("customer_phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discount_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("order_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("payment_method")
                        .HasColumnType("int");

                    b.Property<int>("payment_status")
                        .HasColumnType("int");

                    b.Property<string>("shipping_address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("shipping_fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("sub_total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("order_code")
                        .IsUnique();

                    b.HasIndex("status", "created_date");

                    b.HasIndex("user_id", "created_date");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.OrderItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discount_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("line_total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("product_variant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("unit_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("variant_name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_variant_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Payment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("method")
                        .HasColumnType("int");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("raw_response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("transaction_code")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("transaction_code")
                        .IsUnique()
                        .HasFilter("[transaction_code] IS NOT NULL");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("base_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("brand_id")
                        .HasColumnType("bigint");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_featured")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(270)
                        .HasColumnType("nvarchar(270)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("brand_id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.HasIndex("category_id", "status");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.ProductImage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("display_order")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("is_primary")
                        .HasColumnType("bit");

                    b.Property<long>("product_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("product_variant_id")
                        .HasColumnType("bigint");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("product_variant_id");

                    b.HasIndex("product_id", "display_order");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.ProductVariant", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("cost_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("product_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("sale_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("value_json")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("sku")
                        .IsUnique();

                    b.HasIndex("product_id", "is_active");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("CK_product_variants_value_json", "[value_json] IS NULL OR ISJSON([value_json]) = 1");
                        });
                });

            modelBuilder.Entity("sporthub.domain.RefreshTokens", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("audience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("device_name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<long?>("replaced_by_token_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("replaced_by_token_id");

                    b.HasIndex("token_hash")
                        .IsUnique();

                    b.HasIndex("user_id", "expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Roles", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.UserRole", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Users", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("avatar_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("deleted_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<long>("updated_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("sporthub.domain.Address", b =>
                {
                    b.HasOne("sporthub.domain.Users", "user")
                        .WithMany("addresses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("sporthub.domain.Cart", b =>
                {
                    b.HasOne("sporthub.domain.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("sporthub.domain.CartItem", b =>
                {
                    b.HasOne("sporthub.domain.Cart", "cart")
                        .WithMany("items")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sporthub.domain.ProductVariant", "product_variant")
                        .WithMany()
                        .HasForeignKey("product_variant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("product_variant");
                });

            modelBuilder.Entity("sporthub.domain.Category", b =>
                {
                    b.HasOne("sporthub.domain.Category", "parent")
                        .WithMany("children")
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent");
                });

            modelBuilder.Entity("sporthub.domain.InventoryItem", b =>
                {
                    b.HasOne("sporthub.domain.ProductVariant", "product_variant")
                        .WithOne("inventory")
                        .HasForeignKey("sporthub.domain.InventoryItem", "product_variant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("product_variant");
                });

            modelBuilder.Entity("sporthub.domain.InventoryTransaction", b =>
                {
                    b.HasOne("sporthub.domain.Users", null)
                        .WithMany()
                        .HasForeignKey("created_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sporthub.domain.InventoryItem", "inventory_item")
                        .WithMany("transactions")
                        .HasForeignKey("inventory_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("inventory_item");
                });

            modelBuilder.Entity("sporthub.domain.Order", b =>
                {
                    b.HasOne("sporthub.domain.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("sporthub.domain.OrderItem", b =>
                {
                    b.HasOne("sporthub.domain.Order", "order")
                        .WithMany("items")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sporthub.domain.ProductVariant", "product_variant")
                        .WithMany()
                        .HasForeignKey("product_variant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product_variant");
                });

            modelBuilder.Entity("sporthub.domain.Payment", b =>
                {
                    b.HasOne("sporthub.domain.Order", "order")
                        .WithMany("payments")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("sporthub.domain.Product", b =>
                {
                    b.HasOne("sporthub.domain.Brand", "brand")
                        .WithMany("products")
                        .HasForeignKey("brand_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sporthub.domain.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("brand");

                    b.Navigation("category");
                });

            modelBuilder.Entity("sporthub.domain.ProductImage", b =>
                {
                    b.HasOne("sporthub.domain.Product", "product")
                        .WithMany("images")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sporthub.domain.ProductVariant", "product_variant")
                        .WithMany("Images")
                        .HasForeignKey("product_variant_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("product");

                    b.Navigation("product_variant");
                });

            modelBuilder.Entity("sporthub.domain.ProductVariant", b =>
                {
                    b.HasOne("sporthub.domain.Product", "product")
                        .WithMany("variants")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("sporthub.domain.RefreshTokens", b =>
                {
                    b.HasOne("sporthub.domain.RefreshTokens", "replaced_by_token")
                        .WithMany()
                        .HasForeignKey("replaced_by_token_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sporthub.domain.Users", "user")
                        .WithMany("refresh_tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("replaced_by_token");

                    b.Navigation("user");
                });

            modelBuilder.Entity("sporthub.domain.UserRole", b =>
                {
                    b.HasOne("sporthub.domain.Roles", "roles")
                        .WithMany("user_roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sporthub.domain.Users", "users")
                        .WithMany("user_roles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("roles");

                    b.Navigation("users");
                });

            modelBuilder.Entity("sporthub.domain.Brand", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("sporthub.domain.Cart", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("sporthub.domain.Category", b =>
                {
                    b.Navigation("children");

                    b.Navigation("products");
                });

            modelBuilder.Entity("sporthub.domain.InventoryItem", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("sporthub.domain.Order", b =>
                {
                    b.Navigation("items");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("sporthub.domain.Product", b =>
                {
                    b.Navigation("images");

                    b.Navigation("variants");
                });

            modelBuilder.Entity("sporthub.domain.ProductVariant", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("inventory");
                });

            modelBuilder.Entity("sporthub.domain.Roles", b =>
                {
                    b.Navigation("user_roles");
                });

            modelBuilder.Entity("sporthub.domain.Users", b =>
                {
                    b.Navigation("addresses");

                    b.Navigation("refresh_tokens");

                    b.Navigation("user_roles");
                });
#pragma warning restore 612, 618
        }
    }
}
